In [ ]:
import numpy as np
import array
import pandas as pd

In [ ]:
A = np.array([1,2,3,4,5,6,7,8,9])
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)
print(type(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
C = np.array([[[1,2,],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(C)
print(type(C))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
<class 'numpy.ndarray'>


In [ ]:
print(A[3])

4


In [ ]:
print(B[2,1])

6


In [ ]:
print(C[2,2,1])

18


In [ ]:
print(C[-1,-1,-1])

18


In [ ]:
print(A[1:5])

[2 3 4 5]


In [ ]:
print(A[:5])

[1 2 3 4 5]


In [ ]:
print(A[3:])

[4 5 6 7 8 9]


In [ ]:
print(B[2,2:4])

[9]


In [ ]:
fruit = np.array(['banana','apple','cherry','orange'])

In [ ]:
A1=A.reshape(3,3)
C1=C.reshape(-1)

In [ ]:
for x in A:
  print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in B:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in C:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [ ]:
A3 = 5*A
print(A)
print(A3)
A3 = np.concatenate((A,A3))

[1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45]


In [ ]:
P = np.array([[1,2,3],[4,5,6]])
Q = np.array([[2,-7,5],[-6,2,0]])
R = np.multiply(P,Q)

In [ ]:
P = np.array([[1,2,3],[4,5,6]])
Q = np.array([[2,-7],[-6,2],[1,5]])
R = np.dot(P,Q)

In [ ]:
np.square(B)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
np.sum(C)

171

In [ ]:
print(np.reciprocal(np.sqrt((np.exp(C)-1))))

[[[7.62873978e-01 3.95623107e-01]
  [2.28901063e-01 1.36591948e-01]
  [8.23629462e-02 4.98488882e-02]]

 [[3.02111611e-02 1.83187118e-02]
  [1.11096821e-02 6.73809996e-03]
  [4.08680557e-03 2.47875979e-03]]

 [[1.50344089e-03 9.11882345e-04]
  [5.53084455e-04 3.35462647e-04]
  [2.03468373e-04 1.23409805e-04]]]


In [ ]:
df = pd.read_csv(r'nba.csv')

In [ ]:
df.head(10)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8   Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   
9   Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5                NaN  12000000.0  
6                LSU   1170960.0  
7            Gonzaga   2165160.0  
8         Louisville   1824360.0  
9     Oklahoma State   3431040.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [ ]:
df['Team']

0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...      
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: object

In [ ]:
df.iloc[9]

Name          Marcus Smart
Team        Boston Celtics
Number                36.0
Position                PG
Age                   22.0
Height                 6-4
Weight               220.0
College     Oklahoma State
Salary           3431040.0
Name: 9, dtype: object

In [ ]:
df[df['Age']>25]

Name            Team  Number Position   Age Height  Weight  \
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
11   Isaiah Thomas  Boston Celtics     4.0       PG  27.0    5-9   185.0   
12     Evan Turner  Boston Celtics    11.0       SG  27.0    6-7   220.0   
..             ...             ...     ...      ...   ...    ...     ...   
450     Joe Ingles       Utah Jazz     2.0       SF  28.0    6-8   226.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

               College      Salary  
2    Boston University         NaN  
4                  NaN   5000000.0  
5                  NaN  12000000.0  
11          Washington   6912869.0  
12          Ohio State   3425510.0  
..                 ...         ...  
450                NaN   2050000.0  
451             Dayton    981348.0  
453             Butler   2433333.0  
455                NaN   2900000.0  
456             Kansas    947276.0  

[258 rows x 9 columns]

In [ ]:
df[df['Age']>25 & df['Team'].isin(['Boston Celtics','Utah Jazz'])]

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  

[457 rows x 9 columns]

In [ ]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64